server:
  port: 80
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: inoutkrw
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
#      default_schema: BTCKOREADB_OWN
config:
  clients:
    settle-bank:
      base-url: https://settle-base-url.com