spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        default_schema: BTCKOREADB_OWN
      show-sql: true
logging:
  level:
    com: debug
    org.hibernate:SQL: DEBUG
    org.hibernate.type: trace # SQL